### ISSUE TITLE
Tessel 2 support?

### ISSUE THREAD

**Issue by tlrobinson** [hybridgroup/cylon-tessel#18]
Tessel 2 doesn't appear to work. Looks like it's at least in part due to https://github.com/tessel/t2-cli/issues/653 

```
 cylon-example-tessel git:(master) t2 run script.js
INFO Looking for your Tessel...
INFO Connected to Tessel-x.
INFO Building project.
WARN Pre-compiled module is missing: usb.
This might be caused by any of the following:

1. The binary is platform specific and cannot be compiled for OpenWRT.
2. A pre-compiled binary has not yet been generated for this module.
3. The binary didn't compile correctly for the platform that you're developing on.
    It's possible that the binary is Linux-only or even OpenWRT specific,
    try npm installing with "--force" and rerun your deployment command.

Please file an issue at https://github.com/tessel/t2-cli/issues/new
INFO Writing project to RAM on Tessel-x (68.096 kB)...
INFO Deployed.
INFO Running script.js...
module.js:339
    throw err;
    ^

Error: Cannot find module './lib/config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at r (/tmp/remote-script/node_modules/cylon/index.js:1:97)
    at Object.<anonymous> (/tmp/remote-script/node_modules/cylon/index.js:1:127)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by deadprogram** [comment]
Hi @tlrobinson I've just received a couple of T2's so I'll try to take a look at them this weekend.
